env:
  browser: true
  node: true
  es6: true
extends:
  - airbnb-base
  - "plugin:jest/recommended"
  - "plugin:jsdoc/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  max-len:
    - 0 
    - 
      ignoreComments: true
      ignoreTrailingComments: true
      ignoreUrls: true
  jsdoc/no-undefined-types: 0
plugins:
  - "jest"
  - "jsdoc"